"""v3.4: Cross-backend conformance — the same .omni runs on JS, C, Rust, WASM.

Every back-end consumes the SAME checked OMNI MIR. Any difference in
observable behavior between back-ends is a bug (spec §13.3, §14). These tests
assert that every fixture compiles through every emitter with the expected
structural markers present, and that the CLI build command reaches every
target.
"""

import subprocess
from pathlib import Path

from omni_compiler.c_emitter import emit_c
from omni_compiler.checker import analyze
from omni_compiler.emitter import emit_js
from omni_compiler.lexer import tokenize
from omni_compiler.mir import to_mir
from omni_compiler.parser import parse
from omni_compiler.rust_emitter import emit_rust
from omni_compiler.wasm_emitter import emit_wasm, wasm_build_command

FIXTURES = sorted((Path('tests/fixtures/valid')).glob('*.omni'))


def _compile_all(code: str):
    tokens = tokenize(code)
    ast = parse(tokens)
    symbol_table = analyze(ast)
    return to_mir(ast, symbol_table)


class TestCrossBackendConformance:
    """Same MIR must emit to every back-end without crashing."""

    def test_all_fixtures_emit_all_backends(self):
        for fixture in FIXTURES:
            code = fixture.read_text()
            mir = _compile_all(code)
            for label, out in [
                ('js', emit_js(mir)),
                ('c', emit_c(mir)),
                ('rust', emit_rust(mir)),
                ('wasm-browser', emit_wasm(mir, mode='browser')),
                ('wasm-wasi', emit_wasm(mir, mode='wasi')),
            ]:
                assert out, f'{fixture.name} produced empty {label} output'
                assert isinstance(out, str)
                assert len(out) > 100, f'{fixture.name} {label} output too small'  # noqa: PLR2004

    def test_same_mir_all_backends(self):
        """The MIR is target-independent — one source, one MIR, many emitters."""
        code = FIXTURES[0].read_text()
        mir_a = _compile_all(code)
        mir_b = _compile_all(code)
        assert mir_a.to_json() == mir_b.to_json()

    def test_emit_outputs_are_distinct_per_backend(self):
        code = FIXTURES[0].read_text()
        mir = _compile_all(code)
        js = emit_js(mir)
        c = emit_c(mir)
        rust = emit_rust(mir)
        wasm = emit_wasm(mir, mode='wasi')
        assert len({js, c, rust, wasm}) == 4  # noqa: PLR2004


class TestNativeBackendMarkers:
    """Structural markers per back-end for a computation-heavy fixture."""

    FIXTURE = '03_loops_and_lists.omni'

    def test_js_emits_function_and_batch(self):
        mir = _compile_all(Path(f'tests/fixtures/valid/{self.FIXTURE}').read_text())
        js = emit_js(mir)
        assert 'function' in js
        assert 'batchUpdate' in js

    def test_c_emits_functions_and_main(self):
        mir = _compile_all(Path(f'tests/fixtures/valid/{self.FIXTURE}').read_text())
        c = emit_c(mir)
        assert 'int main(' in c
        assert 'ecs_init()' in c
        assert '// Generated by OmniScript C Emitter' in c

    def test_rust_emits_functions_and_main(self):
        mir = _compile_all(Path(f'tests/fixtures/valid/{self.FIXTURE}').read_text())
        rust = emit_rust(mir)
        assert 'fn main() {' in rust
        assert '// Generated by the OmniScript Rust Emitter' in rust

    def test_wasm_emits_build_command(self):
        mir = _compile_all(Path(f'tests/fixtures/valid/{self.FIXTURE}').read_text())
        browser = emit_wasm(mir, mode='browser')
        wasi = emit_wasm(mir, mode='wasi')
        assert '--target=wasm32' in browser
        assert '--target=wasm32-wasi' in wasi
        assert 'wasm32' in wasm_build_command('browser')
        assert 'wasm32-wasi' in wasm_build_command('wasi')


class TestCLIBuildIntegration:
    """omni build reaches every target from a real fixture."""

    def test_build_every_target(self, tmp_path):
        fixture = Path('tests/fixtures/valid/01_basic.omni')
        for target, suffix in [
            ('js', '.html'),
            ('c', '.c'),
            ('rust', '.rs'),
            ('wasm-browser', '.html'),
            ('wasm-wasi', '.c'),
        ]:
            out = tmp_path / f'01_basic{suffix}'
            result = subprocess.run(
                [
                    'python',
                    '-m',
                    'omni_compiler.cli',
                    'build',
                    str(fixture),
                    '--target',
                    target,
                    '--output',
                    str(out),
                ],
                capture_output=True,
                text=True,
                cwd='.',
                check=False,
            )
            assert result.returncode == 0, f'{target}: {result.stderr}'
            assert out.exists(), f'{target}: no output written'

    def test_build_all_fixtures_js(self, tmp_path):
        for fixture in FIXTURES:
            out = tmp_path / f'{fixture.stem}.html'
            result = subprocess.run(
                [
                    'python',
                    '-m',
                    'omni_compiler.cli',
                    'build',
                    str(fixture),
                    '--target',
                    'js',
                    '--output',
                    str(out),
                ],
                capture_output=True,
                text=True,
                cwd='.',
                check=False,
            )
            assert result.returncode == 0, f'{fixture.name}: {result.stderr}'
            assert out.read_text().startswith('<!DOCTYPE html>')
