#!/usr/bin/env python3
"""Generate docs/INDEX.md from the docs/ tree.

Usage:
    python scripts/gen-index.py           # write docs/INDEX.md
    python scripts/gen-index.py --check   # exit 1 if docs/INDEX.md is out of sync
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / "docs"
INDEX = DOCS / "INDEX.md"

BANNER = (
    "<!-- AUTO-GENERATED by scripts/gen-index.py - do not edit. "
    "Regenerate with: python scripts/gen-index.py -->"
)

MODULE_ORDER = [
    "core", "ui", "db", "graphics", "gpu", "net", "http", "audio", "video",
    "fs", "crypto", "auth", "sim", "ai", "test", "async", "platform", "scene",
]


def _purpose_summary(module_file: Path) -> str:
    text = module_file.read_text(encoding="utf-8")
    match = re.search(r"## Purpose\s*\n+(.*?)(?=\n## |\Z)", text, re.S)
    if not match:
        return "No purpose stated"
    first = next((ln for ln in match.group(1).splitlines() if ln.strip()), "")
    summary = re.sub(r"^[-*]\s*", "", first).strip()
    return summary[:120] + ("..." if len(summary) > 120 else "")


def generate() -> str:
    lines = [BANNER, "", "# Documentation Index", ""]
    lines.append("Generated navigation index for everything under `docs/`.")
    lines.append("")

    lines.append("## Generated Files")
    lines.append("")
    lines.append("- [CAPABILITY_MATRIX.md](CAPABILITY_MATRIX.md) - module capability matrix")
    lines.append("")
    lines.append("## Conventions")
    lines.append("")
    lines.append("- [DOC_CONVENTIONS.md](DOC_CONVENTIONS.md) - template and rules")

    sections = {
        "language": "## Language",
        "architecture": "## Architecture",
        "decisions": "## Decisions",
        "omnisys": "## OMNISYS Modules",
    }

    for folder, heading in sections.items():
        lines.append("")
        lines.append(heading)
        lines.append("")
        readme = DOCS / folder / "README.md"
        if readme.exists():
            rel = readme.relative_to(DOCS).as_posix()
            lines.append(f"- [{folder}/README.md]({rel}) - directory index")
            lines.append("")

    lines.append("### Module READMEs")
    lines.append("")
    for module in MODULE_ORDER:
        module_file = DOCS / "omnisys" / module / "README.md"
        if module_file.exists():
            rel = module_file.relative_to(DOCS).as_posix()
            lines.append(f"- [{module}]({rel}) - {_purpose_summary(module_file)}")
    lines.append("")

    return "\n".join(lines)


def main() -> int:
    content = generate()
    if "--check" in sys.argv:
        if INDEX.exists() and INDEX.read_text(encoding="utf-8") == content:
            return 0
        print("INDEX.md is out of sync - run python scripts/gen-index.py")
        return 1
    INDEX.write_text(content, encoding="utf-8")
    print(f"wrote {INDEX.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())