#!/usr/bin/env python3
"""Generate docs/CAPABILITY_MATRIX.md from module README CAPABILITIES tags.

Usage:
    python scripts/gen-capability-matrix.py           # write docs/CAPABILITY_MATRIX.md
    python scripts/gen-capability-matrix.py --check   # exit 1 if out of sync
"""

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
DOCS = ROOT / 'docs'
OUTPUT = DOCS / 'CAPABILITY_MATRIX.md'

BANNER = (
    '<!-- AUTO-GENERATED by scripts/gen-capability-matrix.py - do not edit. '
    'Regenerate with: python scripts/gen-capability-matrix.py -->'
)

MODULE_ORDER = [
    'core', 'ui', 'db', 'graphics', 'gpu', 'net', 'http', 'audio', 'video',
    'fs', 'crypto', 'auth', 'sim', 'ai', 'test', 'async', 'platform', 'scene',
]

TAG_RE = re.compile(r'<!--\s*CAPABILITIES:\s*(.*?)\s*-->')


def module_capabilities(module: str) -> list[str]:
    path = DOCS / 'omnisys' / module / 'README.md'
    if not path.exists():
        return []
    text = path.read_text(encoding='utf-8')
    match = TAG_RE.search(text)
    if not match:
        return []
    return [tag.strip() for tag in match.group(1).split(';') if tag.strip()]


def generate() -> str:
    lines = [BANNER, '', '# Capability Matrix', '']
    lines.append('Capabilities used by each OMNISYS module, derived from')
    lines.append('`<!-- CAPABILITIES: ... -->` tags in the module READMEs.')
    lines.append('')
    lines.append('| Module | Capabilities |')
    lines.append('|--------|--------------|')
    for module in MODULE_ORDER:
        caps = module_capabilities(module)
        lines.append(f"| {module} | {', '.join(caps) if caps else '-'} |")
    lines.append('')
    return '\n'.join(lines)


def main() -> int:
    content = generate()
    if '--check' in sys.argv:
        if OUTPUT.exists() and OUTPUT.read_text(encoding='utf-8') == content:
            return 0
        print('CAPABILITY_MATRIX.md is out of sync - run python scripts/gen-capability-matrix.py')
        return 1
    OUTPUT.write_text(content, encoding='utf-8')
    print(f'wrote {OUTPUT.relative_to(ROOT)}')
    return 0


if __name__ == '__main__':
    sys.exit(main())